# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:03:45+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity

from models import Movie

app = MCPProxy(
    description='Create and edit awesome videos programmatically',
    title='JSON2Video API',
    version='2.0.0',
    servers=[
        {'description': 'Version 2 endpoint', 'url': 'https://api.json2video.com/v2'}
    ],
)


@app.get(
    '/movies',
    description=""" Get the status any of your movies by passing your project ID in the <code>project</code> query parameter. You can get your project ID from the response of the POST request. """,
    tags=['movie_management'],
)
def get_movies():
    """
    Get the status of your movies
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/movies',
    description=""" Submit a new movie rendering job. """,
    tags=['movie_management'],
)
def new_movie(body: Movie):
    """
    Create a new movie
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
