# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:03:45+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, confloat, conint


class AudioElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    muted: Optional[bool] = Field(False, description='Mutes the audio')
    volume: Optional[confloat(ge=0.0, le=10.0)] = 5


class BaseElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cache: Optional[bool] = Field(
        True,
        description="Element's cache policy. When true, the cached version (if exists) is used. When false, the assets is downloaded.",
        examples=[False],
    )
    comment: Optional[str] = Field(None, description='Used for adding your comments')
    duration: Optional[float] = Field(
        -1,
        description="Element's duration in seconds. A value of -1 auto calculates the duration based on the asset intrinsic length or the scene duration.",
        examples=[7.3],
    )
    extra_time: Optional[float] = Field(
        0,
        alias='extra-time',
        description="Element's time span added after the playback.",
        examples=[0.5],
    )
    fade_in: Optional[confloat(ge=0.0)] = Field(
        None,
        alias='fade-in',
        description='Adds a fade in effect to the element. Value in seconds.',
    )
    fade_out: Optional[confloat(ge=0.0)] = Field(
        None,
        alias='fade-out',
        description='Adds a fade out effect to the element. Value in seconds.',
    )
    start: Optional[float] = Field(
        0,
        description="Element's starting time in seconds relative to the container scene or the movie if the element is in the Movie's elements array.",
    )
    z_index: Optional[float] = Field(
        0,
        alias='z-index',
        description="Element's z-index. Use this property to reorganize the layering of the elements like in HTML",
        examples=[3],
    )


class Capture(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    duration: Optional[confloat(ge=0.0, le=10.0)] = Field(
        0,
        description='Screen recording duration in seconds. Use 0 to take a screenshot',
    )
    height: conint(ge=50, le=1080) = Field(..., description='Viewport height')
    width: conint(ge=50, le=1920) = Field(..., description='Viewport width')


class CaptureProperty(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capture: Optional[Capture] = Field(None, description='Browser capture settings')


class ChromaKey(BaseModel):
    color: str = Field(
        ...,
        description='Set the color for which alpha will be set to 0 (full transparency)',
        examples=['#00b140'],
    )
    tolerance: Optional[conint(ge=1, le=100)] = Field(
        25,
        description='Makes the selection more or less sensitive to changes in color. A value of 1 will select only the provided color. A value of 100 will select all colors, so the full canvas',
    )


class Crop(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    height: int = Field(..., description='Sets the height of the croping')
    width: int = Field(..., description='Sets the width of the croping')
    x: Optional[int] = Field(0, description='Sets the left point of croping')
    y: Optional[int] = Field(0, description='Sets the top point of croping')


class Pan(Enum):
    left = 'left'
    top = 'top'
    right = 'right'
    bottom = 'bottom'
    top_left = 'top-left'
    top_right = 'top-right'
    bottom_left = 'bottom-left'
    bottom_right = 'bottom-right'


class Position(Enum):
    top_left = 'top-left'
    top_right = 'top-right'
    bottom_right = 'bottom-right'
    bottom_left = 'bottom-left'
    center_center = 'center-center'
    custom = 'custom'


class Rotate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    angle: confloat(ge=-360.0, le=360.0) = Field(
        ..., description='Sets the angle of rotation'
    )
    speed: Optional[confloat(ge=0.0)] = Field(
        0,
        description='Sets the time it takes to rotate the provided angle. A zero value means no movement',
    )


class Scale(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    height: Optional[conint(ge=-1)] = Field(
        -1, description='Sets the height for scaling the element'
    )
    width: Optional[conint(ge=-1)] = Field(
        -1, description='Sets the width for scaling the element'
    )


class VisualElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chroma_key: Optional[ChromaKey] = Field(
        None,
        alias='chroma-key',
        description='Allows to define a color (or a range of colors) that will be converted to transparent',
    )
    crop: Optional[Crop] = Field(None, description='Crops the element')
    pan: Optional[Pan] = Field(
        None,
        description='Pans the element to the specified direction. If <code>zoom</code> property is not specified, the effect is a non-zooming pan',
    )
    position: Optional[Position] = Field(
        'custom',
        description="Sets the element position in the scene. A value of 'custom' sets a custom position based on the provided 'x' and 'y' properties",
    )
    rotate: Optional[Rotate] = None
    scale: Optional[Scale] = None
    x: Optional[float] = Field(
        0,
        description='Sets the horizontal position of the element in the scene. The value <code>0</code> is on the left side',
    )
    y: Optional[float] = Field(
        0,
        description='Sets the vertical position of the element in the scene. The value <code>0</code> is on the top side',
    )
    zoom: Optional[conint(ge=-100, le=100)] = Field(
        None,
        description='Zooms the element with the specified level percentage. Positive values zoom in, negative values zoom out, zero does not zoom. Zoom can be combined with the <code>pan</code> property to set the focus point of the zooming',
    )


class Type(Enum):
    audio = 'audio'


class Audio(BaseElement, AudioElement):
    src: Optional[AnyUrl] = None
    type: Literal['audio']


class Type1(Enum):
    component = 'component'


class Component(BaseElement, VisualElement):
    component: str = Field(
        ...,
        description="ID of the Component element. Check all available components in the <a href='https://json2video.com/docs/resources/basic/'>library</a>",
        examples=['basic/001'],
    )
    height: Optional[conint(ge=-1, le=1080)] = Field(
        -1,
        description='Desired text element height, but can be overriden by the component defaults. A value of <code>-1</code> means inherits scenes or movie height',
    )
    settings: Optional[Dict[str, Any]] = Field(
        None, description='Settings to be passed to the component'
    )
    type: Literal['component']
    width: Optional[conint(ge=-1, le=1920)] = Field(
        -1,
        description='Desired text element width, but can be overriden by the component defaults. A value of <code>-1</code> means inherits scenes or movie width',
    )


class Type2(Enum):
    html = 'html'


class Html(BaseElement, VisualElement):
    height: Optional[conint(ge=-1, le=1080)] = Field(
        -1,
        description='Desired text element height. A value of <code>-1</code> means inherits scenes or movie height',
    )
    html: str = Field(
        ...,
        description='HTML snippet to render. Compatible with HTML5, CSS3 and Javascript',
        examples=['&lt;h1&gt;Hello world&lt;/h1&gt;'],
    )
    tailwindcss: Optional[bool] = Field(
        False,
        description='Enables usage of TailwindCSS for the HTML snippet',
        examples=[True],
    )
    type: Literal['html']
    width: Optional[conint(ge=-1, le=1920)] = Field(
        -1,
        description='Desired text element width. A value of <code>-1</code> means inherits scenes or movie width',
    )


class Type3(Enum):
    image = 'image'


class Image(VisualElement):
    src: Optional[AnyUrl] = None
    type: Literal['image']


class Draft(Enum):
    boolean_True = True
    boolean_False = False


class Quality(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class Resolution(Enum):
    sd = 'sd'
    hd = 'hd'
    full_hd = 'full-hd'
    squared = 'squared'
    instagram_story = 'instagram-story'
    instagram_feed = 'instagram-feed'
    twitter_landscape = 'twitter-landscape'
    twitter_portrait = 'twitter-portrait'


class Style(Enum):
    fade = 'fade'
    wipeleft = 'wipeleft'
    wiperight = 'wiperight'
    wipeup = 'wipeup'
    wipedown = 'wipedown'
    slideleft = 'slideleft'
    slideright = 'slideright'
    slideup = 'slideup'
    slidedown = 'slidedown'
    circlecrop = 'circlecrop'
    rectcrop = 'rectcrop'
    distance = 'distance'
    fadeblack = 'fadeblack'
    fadewhite = 'fadewhite'
    radial = 'radial'
    smoothleft = 'smoothleft'
    smoothright = 'smoothright'
    smoothup = 'smoothup'
    smoothdown = 'smoothdown'
    circleopen = 'circleopen'
    circleclose = 'circleclose'
    vertopen = 'vertopen'
    vertclose = 'vertclose'
    horzopen = 'horzopen'
    horzclose = 'horzclose'
    dissolve = 'dissolve'
    pixelize = 'pixelize'
    diagtl = 'diagtl'
    diagtr = 'diagtr'
    diagbl = 'diagbl'
    diagbr = 'diagbr'
    hlslice = 'hlslice'
    hrslice = 'hrslice'
    vuslice = 'vuslice'
    vdslice = 'vdslice'
    hblur = 'hblur'
    fadegrays = 'fadegrays'
    wipetl = 'wipetl'
    wipetr = 'wipetr'
    wipebl = 'wipebl'
    wipebr = 'wipebr'
    squeezeh = 'squeezeh'
    squeezev = 'squeezev'
    zoomin = 'zoomin'


class Type4(Enum):
    xfade = 'xfade'


class Transition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    duration: Optional[float] = Field(
        None, description='Duration of the transition in seconds', examples=[1.5]
    )
    style: Optional[Style] = Field('fade', examples=['circleopen'])
    type: Optional[Type4] = 'xfade'


class Type5(Enum):
    template = 'template'


class Template(BaseElement, VisualElement):
    height: Optional[conint(ge=-1, le=1080)] = Field(
        -1,
        description='Desired text element height, but can be overriden by the component defaults. A value of <code>-1</code> means inherits scenes or movie height',
    )
    settings: Optional[Dict[str, Any]] = Field(
        None, description='Settings to be passed to the component'
    )
    template: str = Field(
        ...,
        description="ID of the Component element. Check all available components at <a href='https://json2video.com/docs/resources/basic/'>https://json2video.com/docs/resources/basic/</a>",
        examples=['basic/001'],
    )
    type: Literal['template']
    width: Optional[conint(ge=-1, le=1920)] = Field(
        -1,
        description='Desired text element width, but can be overriden by the component defaults. A value of <code>-1</code> means inherits scenes or movie width',
    )


class Type6(Enum):
    text = 'text'


class Text(BaseElement, VisualElement):
    height: Optional[conint(ge=-1, le=1080)] = Field(
        -1,
        description='Desired text element height, but can be overriden by the style defaults. A value of <code>-1</code> means inherits scenes or movie height',
    )
    settings: Optional[Dict[str, Any]] = Field(
        {},
        description='Text formatting settings. In general, these are CSS properties such as <code>font-size</code>, <code>colour</code> or <code>font-weight</code>. See the styles to confirm which properties are available.',
        examples=[{'color': '#FF0000', 'font-size': '60px'}],
    )
    style: Optional[str] = Field(
        '001',
        description="Style of the text element. Check all available text style at <a href='https://json2video.com/docs/resources/text/'>https://json2video.com/resources/text/</a>",
        examples=['003'],
    )
    text: str = Field(
        ...,
        description='Text to be printed. The text string does not accept HTML formatting.',
        examples=['Lorem ipsum dolor sit amet'],
    )
    type: Literal['text']
    width: Optional[conint(ge=-1, le=1920)] = Field(
        -1,
        description='Desired text element width, but can be overriden by the style defaults. A value of <code>-1</code> means inherits scenes or movie width',
    )


class Type7(Enum):
    video = 'video'


class Video(BaseElement, VisualElement, AudioElement):
    src: Optional[AnyUrl] = Field(
        None,
        description='URL to the asset file. Videos can be in MP4, MKV, MOV but MP4 is recommended.',
    )
    type: Literal['video']
    loop: Optional[conint(ge=-1)] = Field(
        None,
        description='Sets the number of loops the video to play. Use -1 for an infinite loop. The default value of 1 plays the video just once.',
        examples=[-1],
    )


class Type8(Enum):
    voice = 'voice'


class Voice(BaseElement, AudioElement):
    text: str = Field(
        ..., description='The sentence or sentences to be converted to voice audio'
    )
    type: Literal['voice']
    voice: Optional[str] = Field(
        'en-GB-LibbyNeural',
        description='The voice name to be used. Check <a href="/docs/tutorial/voice-elements/">available voices</a>.',
    )


class Elements(
    RootModel[Union[Video, Image, Text, Html, Component, Template, Audio, Voice]]
):
    root: Union[Video, Image, Text, Html, Component, Template, Audio, Voice] = Field(
        ..., discriminator='type'
    )


class Elements1(RootModel[Union[Video, Image, Text, Html, Component, Audio, Voice]]):
    root: Union[Video, Image, Text, Html, Component, Audio, Voice] = Field(
        ..., discriminator='type'
    )


class Scene(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    background_color: Optional[str] = Field(
        '#000000',
        alias='background-color',
        description="A hexadecimal representation of a color or 'transparent'",
        examples=['#FF0000'],
    )
    cache: Optional[bool] = True
    comment: Optional[str] = Field(None, description='Used for adding your comments')
    duration: Optional[float] = -1
    elements: Optional[List[Elements1]] = None
    transition: Optional[Transition] = None


class Movie(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cache: Optional[bool] = True
    comment: Optional[str] = Field(None, description='Used for adding your comments')
    draft: Optional[Draft] = Field(
        True,
        description='Draft movies include a watermark. Check your plan how many draft and final movies you have',
    )
    elements: Optional[List[Elements]] = None
    fps: Optional[int] = Field(25, description='Frames per second')
    height: Optional[conint(ge=50, le=1080)] = Field(360, examples=[360])
    quality: Optional[Quality] = 'high'
    resolution: Optional[Resolution] = None
    scenes: List[Scene]
    settings: Optional[Dict[str, Any]] = Field(
        {}, description='Movie advanced settings'
    )
    width: Optional[conint(ge=50, le=1920)] = Field(640, examples=[640])
